import { useRouter } from 'next/router'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { useEffect } from 'react'


export default function Home() {

  useEffect(() => {
    console.log('hello from effect', process.env.testlocal)
  },[])

  const router = useRouter()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Mixter Client Experiments
        </h1>

        <div className={styles.grid}>
          <a className={styles.card} onClick={() => router.push('/callapi')}>
            <h2>Retrieve webpage &rarr;</h2>
            <p>testing cors on client, and sanitizing/displaying html from axios get request</p>
          </a>

          <a className={styles.card} onClick={() => router.push('/voicetotext')}>
            <h2>Text to Voice &rarr;</h2>
            <p>testing text to speech</p>
          </a>

          <a className={styles.card} onClick={() => router.push('/s3upload')}>
            <h2>S3 Upload &rarr;</h2>
            <p>testing amazon sdk s3 uploads</p>
          </a>
        </div>
      </main>


    </div>
  )
}

export async function getServerSideProps(){

  console.log(process.env.testlocal)
  return {
    props:{
      hello: 'world'
    }
  }
}
