import { useRouter } from 'next/router'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'


export default function Home() {

  const router = useRouter()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Mixter Client Experiments
        </h1>

        <div className={styles.grid}>
          <a className={styles.card} onClick={() => router.push('/callapi')}>
            <h2>Retrieve webpage &rarr;</h2>
            <p>testing cors on client, and sanitizing/displaying html from axios get request</p>
          </a>

          <a className={styles.card} onClick={() => router.push('/voicetotext')}>
            <h2>Text to Voice &rarr;</h2>
            <p>testing voice to text</p>
          </a>
        </div>
      </main>


    </div>
  )
}
